name: dotnet package

on: 
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build ABBWorkItemClone
        shell: pwsh
        run: .\build.ps1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: ABBWorkItemClone
          path: .\output\*


