name: dotnet package

on: 
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Script
        shell: pwsh
        run: .\build.ps1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
