name: ABBWorkItemClone Build and Release

on: 
  push:
  workflow_dispatch:

jobs:
  Setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      GitVersion_BranchName: ${{ steps.gitversion.outputs.GitVersion_BranchName }}
      GitVersion_SemVer: ${{ steps.gitversion.outputs.GitVersion_SemVer }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'
    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1
      with:
        useConfigFile: true

  build:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - run: dotnet build
      - run: dotnet test
      - run: 'Get-ChildItem -Directory -Recurse' 
        shell: pwsh
      - run: 'Get-ChildItem -Directory -Recurse -Path ./'
        shell: pwsh
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -tzip ./output/ABBWorkItemClone-v${{needs.Setup.outputs.GitVersion_SemVer}}.zip /home/runner/work/abb-workitem-clone/abb-workitem-clone/ABB.WorkItemClone.AzureDevOps/bin/Debug/net8.0/**
      - uses: actions/upload-artifact@v4
        with:
          name: ABBWorkItemClone
          path: ./output/*
      
  release:
    runs-on: ubuntu-latest
    needs: [build, Setup]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ABBWorkItemClone
      - run: gh release create v${{needs.Setup.outputs.GitVersion_SemVer}} .\output\ABBWorkItemClone-v${{needs.Setup.outputs.GitVersion_SemVer}}.zip --generate-notes --generate-notes --discussion-category "General"
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


